version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db
    env_file: 
      - backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    container_name: xtramiles_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "8080:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]

  # frontend:
  #   build: ./frontend
  #   restart: always
  #   container_name: xtramiles_frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "${FRONTEND_PORT}:3000"

volumes:
  db_data:
